export const GET_DEVICES = 'GET_DEVICES';
export const ADD_DEVICE = 'ADD_DEVICE';
export const GET_SINGLE_DEVICE = 'GET_SINGLE_DEVICE';
export const DELETE_DEVICE = 'DELETE_DEVICE';
export const UPDATE_DEVICE = 'UPDATE_DEVICE';